all: rational hashmat reverse bricks


rational: rational.cc
	g++ rational.cc -lm -o rational

hashmat: hashmat.cc
	g++ hashmat.cc -lm -o hashmat

reverse: reverse.cc
	g++ reverse.cc -lm -o  reverse

bricks: bricks.cc
	g++ bricks.cc -lm -o bricks

clean:
	del rational.exe
	del hashmat.exe
	del reverse.exe
	del bricks.exe
	del artichokes.exe
	del *~
